### ISSUE TITLE
Segmentation fault after compiling with MinGW

### ISSUE THREAD

**Issue by lordlouckster** [justNo4b/Equisetum#43]
More specifically WinLibs, gcc 14.1.
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff7905b2619 in void std::_Construct<Search, Board&, Limits&, Hist&, OrderingInfo*&>(Search*, Board&, Limits&, Hist&, OrderingInfo*&) ()
```

**Comment by lordlouckster** [comment]
Full GDB backtrace from another build:
```
#0  0x00007ff66fce2619 in void std::_Construct<Search, Board&, Limits&, Hist&, OrderingInfo*&>(Search*, Board&, Limits&, Hist&, OrderingInfo*&) ()
#1  0x00007ff66fce26f9 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Search, std::allocator<void>, Board&, Limits&, Hist&, OrderingInfo*&>(Search*&, std::_Sp_alloc_shared_tag<std::allocator<void> >, Board&, Limits&, Hist&, OrderingInfo*&) ()
#2  0x00007ff66fce274d in std::shared_ptr<Search>::shared_ptr<std::allocator<void>, Board&, Limits&, Hist&, OrderingInfo*&>(std::_Sp_alloc_shared_tag<std::allocator<void> >, Board&, Limits&, Hist&, OrderingInfo*&) ()
#3  0x00007ff66fce2b4c in (anonymous namespace)::go(std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >&) ()
#4  0x00007ff66fce6b1e in (anonymous namespace)::loop() ()
#5  0x00007ff66fce6cb1 in Uci::start() ()
#6  0x00007ff66fcdcd1c in main ()
```
Building on MSYS2 and -static, the following error message appears:
```
The procedure link library _ZNSi5seekgESt4pfosliE could not be located in the dynamic link library [...]\Equisetum_dev.exe.
```

**Comment by justNo4b** [comment]
Hello.
Better detection of windows and compilation with mingw would likely be supported on version 2.0
